### ISSUE TITLE
token不定时过期

### ISSUE THREAD

**Issue by aifans** [nutzam/nutzwx#19]
部署了一个在生产环境测试。
目前发现会不定时出现token过期的错误。
invalid credential, access_token is invalid or not latest hint: 

苦恼啊~~我就部署了一个应用，也没开多线程。

**Comment by wendal** [comment]
如果没有规律,那就99%是因为有其他程序获取了access_token

更新一下密钥, 看看能不能解决

**Comment by aifans** [comment]
确实有这个可能。微信支付是另外一个应用，那边可能拿了token。
