### ISSUE TITLE
wxInMsg.getScanCodeInfo();  这个方法会转换异常

### ISSUE THREAD

**Issue by yuffo** [nutzam/nutzwx#33]
这个方法会报转换异常 nuzMap无法转换为 WxScanCodeInfo 

	public WxScanCodeInfo getScanCodeInfo() {
	return (WxScanCodeInfo)get("scanCodeInfo");
    }

我下了源码改了下,在我这暂时能用了,只是我感觉我这样处理还不是很好
public WxScanCodeInfo getScanCodeInfo() {
		NutMap map = (NutMap) get("scanCodeInfo");
		WxScanCodeInfo wxScanCodeInfo = new WxScanCodeInfo();
		wxScanCodeInfo.setScanResult(map.getString("scanResult"));
		wxScanCodeInfo.setScanType(map.getString("scanType"));
		return wxScanCodeInfo;
	}

**Comment by zozoh** [comment]
大约可以 

```java
public WxScanCodeInfo getScanCodeInfo() {
    return this.getAs("scanCodeInfo", WxScanCodeInfo.class);
}
```
