### ISSUE TITLE
WxApi返回WxResp乱码

### ISSUE THREAD

**Issue by loyalove** [nutzam/nutzwx#4]

**Comment by wendal** [comment]
就这样? 什么描述什么代码都没有?????

**Comment by zozoh** [comment]
同问

**Comment by unhappydepig** [comment]
修改:nutzwx/src/main/java/org/nutz/weixin/impl/AbstractWxApi2.java  180行为:
return Json.fromJson(WxResp.class,resp.getReader("utf-8"));

**Comment by wendal** [comment]
开发环境不是UTF-8导致的吧

**Comment by Kerbores** [comment]
这个问题应该按照@unhappydepig的方式处理,微信官方就是按照 UTF8返回的,如果运行环境不是 UTF8的话就乱码了
