### ISSUE TITLE
微信支付

### ISSUE THREAD

**Issue by Coco557** [nutzam/nutzwx#40]
亲爱的开源SDK作者，
您好，检测到您的github中的开源SDK中存在XXE漏洞，请按微信支付官方指引修复：
https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=23_5 ；
存在漏洞的源码路径：
https://github.com/nutzam/nutzwx/blob/master/src/main/java/org/nutz/weixin/repo/com/qq/weixin/mp/aes/XMLParse.java

**Comment by wendal** [comment]
这是已经改好的版本吧? 又有新的修改?

**Comment by Coco557** [comment]
不好意思，打扰到您，还请您后续有时间对应文档进行检查测试一下呢，谢谢~

**Comment by wendal** [comment]
哦,我知道你的意思了
