### ISSUE TITLE
WxApi2Impl类的_mass_send方法实现有误，微信api有更新！请修改！

### ISSUE THREAD

**Issue by wangsenhehe** [nutzam/nutzwx#7]
public WxResp _mass_send(NutMap filter, List<String> to_user, String touser, WxOutMsg msg) {
		NutMap params = new NutMap();
		if (filter != null)
			params.setv("filter", filter);
		else if (to_user != null) {
			params.setv("to_user", to_user);
		} else {
			params.put("touser", touser);
		}
以上的key"to_user"微信貌似已经没有啦，全部都是touser啦！

**Comment by wendal** [comment]
额 @Kerbores 搞搞?

**Comment by Kerbores** [comment]
[已修复](https://github.com/nutzam/nutzwx/commit/931891be75ac5919469e034f21a430b514a746e8)

**Comment by wangsenhehe** [comment]
谢谢！
