### ISSUE TITLE
网页授权功能是否支持呢？

### ISSUE THREAD

**Issue by opendever** [nutzam/nutzwx#9]
[网页授权获取用户基本信息](http://mp.weixin.qq.com/wiki/4/9ac2e7b1f1d22e9e57260f6553822520.html) 
如果支持怎么使用？

**Comment by wendal** [comment]
没有, 我看看怎么实现一下先

**Comment by Wizzercn** [comment]
http://doxmate.cool/node-webot/wechat-api/api.html
求类似的完整API
